title: Baichen Du
position: The pic, me in Tai Mei Tuk, HK
affiliation: The University of Hong Kong, Bachelor of Social Sciences(IV)
email: baichen@connect.hku.hk
#address1: R.C.Lee Hall, 
#address2: 6A Sassoon Road,
#address3: Pokfulam, Hong Kong, HKG
#keywords: minimal academic
#google_scholar: https://scholar.google.com/
#github_link: https://github.com/AlbertBaichenDu
#linkedin: https://www.linkedin.com/
avatar: ./assets/img/profile.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/monogram_round.png
favicon_dark: ./assets/img/monogram_round.png
description: Final Year Linguistic UG Student at The University of Hong Kong
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light

