title: Baichen Du (杜柏辰)
position: Bachelor of Social Sciences IV
affiliation: The University of Hong Kong<br />
affiliation: R.C.Lee Hall,<br />
6A Sassoon Road,<br />
Pokfulam, Hong Kong
affiliation: baichen@connect.hku.hk
affiliation: +852 56964800
#keywords: minimal academic
#google_scholar: https://scholar.google.com/
github_link: https://github.com/AlbertBaichenDu
#linkedin: https://www.linkedin.com/
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/profile.jpg
favicon_dark: ./assets/img/favicon-dark.png
description: 
canonical: 
remote_theme: yaoyao-liu/minimal-light
