title: Baichen Du
position: Bachelor of Social Sciences
affiliation: The University of Hong Kong
email: baichen@connect.hku.hk     +852 56964800
#R.C.Lee Hall, 
#6A Sassoon Road,
#Pokfulam, Hong Kong, HKG
keywords: minimal academic
#google_scholar: https://scholar.google.com/
#github_link: https://github.com/AlbertBaichenDu
#linkedin: https://www.linkedin.com/
avatar: ./assets/img/profile.jpg
google_analytics: UA-111540567-4
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light

